/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVoiceRouteImport } from './routes/dashboard.voice'
import { Route as DashboardSosRouteImport } from './routes/dashboard.sos'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard.records'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMedicineRouteImport } from './routes/dashboard.medicine'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoiceRoute = DashboardVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSosRoute = DashboardSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicineRoute = DashboardMedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/medicine': typeof DashboardMedicineRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/medicine': typeof DashboardMedicineRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/medicine': typeof DashboardMedicineRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sos': typeof DashboardSosRoute
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/medicine'
    | '/dashboard/notifications'
    | '/dashboard/records'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/sos'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/medicine'
    | '/dashboard/notifications'
    | '/dashboard/records'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/sos'
    | '/dashboard/voice'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/medicine'
    | '/dashboard/notifications'
    | '/dashboard/records'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/sos'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voice': {
      id: '/dashboard/voice'
      path: '/voice'
      fullPath: '/dashboard/voice'
      preLoaderRoute: typeof DashboardVoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sos': {
      id: '/dashboard/sos'
      path: '/sos'
      fullPath: '/dashboard/sos'
      preLoaderRoute: typeof DashboardSosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/medicine': {
      id: '/dashboard/medicine'
      path: '/medicine'
      fullPath: '/dashboard/medicine'
      preLoaderRoute: typeof DashboardMedicineRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardMedicineRoute: typeof DashboardMedicineRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSosRoute: typeof DashboardSosRoute
  DashboardVoiceRoute: typeof DashboardVoiceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMedicineRoute: DashboardMedicineRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSosRoute: DashboardSosRoute,
  DashboardVoiceRoute: DashboardVoiceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
